name: 'shopify'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

models:
  shopify:
    all:
        aggregates:
            materialized: ephemeral
        base:
            materialized: ephemeral
    subscription:
        aggregates:
            materialized: ephemeral
        base:
            materialized: ephemeral
    non_subscription:
        aggregates:
            materialized: ephemeral
        base:
            materialized: ephemeral
    source:
        materialized: ephemeral
    filters:
        materialized: ephemeral
  vars:
    source_schema:        shopify # your schema here
    checkouts_table:      checkouts
    users_table:          customers
    orders_table:         orders
    transactions_table:   transactions
    products_table:       products
    refunds_table:        order_refunds
    discount_codes_table: orders__discount_codes
    order_items_table:    orders__line_items
    product_variants_table: products__variants
