name: 'shopify'

config-version: 2
version: '1.0'

profile: lacolombe-dtc

source-paths: ["models"]
#data-paths: [directorypath]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ['macros']
#snapshot-paths: [directorypath]
#docs-paths: [directorypath]
#asset-paths: [directorypath]

target-path: "target"
#log-path: directorypath
#modules-path: directorypath

clean-targets: ["target"]

#query-comment: string

#require-dbt-version: version-range | [version-range]

#quoting:
#  database: true | false
#  schema: true | false
#  identifier: true | false

models:
  shopify:
    aggregates:
        materialized: ephemeral
    base:
        materialized: ephemeral
    source:
        materialized: ephemeral

#seeds:

#snapshots:


#vars:

#on-run-start: sql-statement | [sql-statement]
#on-run-end: sql-statement | [sql-statement]
