version: 2

sources:
  - name: stitch_shopify
    loader: stitch
    description: https://shopify.dev/docs/admin-api/rest/reference
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: _sdc_batched_at

    tables:

    - name: customers
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer
    - name: orders
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: orders__discount_codes
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: orders__line_items
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: orders__line_items__properties
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: orders__fulfillments
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: orders__shipping_lines
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/order
    - name: transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/transaction
    - name: products
      description: https://shopify.dev/docs/admin-api/rest/reference/products/product
    - name: products__variants
      description: https://shopify.dev/docs/admin-api/rest/reference/products/product-variant
    - name: order_refunds
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund
    - name: order_refunds__refund_line_items
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund


models:

  - name: shopify_base_orders

